name: Feature request
description: Suggest an idea for Blooby
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: >
        Describe the situation rather than the solution.
        It usually leads to a better feature than the one we would have guessed.
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: What did you have in mind?
    validations:
      required: false

  - type: checkboxes
    id: checked
    attributes:
      label: Before submitting
      options:
        - label: I searched the existing issues for this idea
          required: true
